services:
  backend:
    build:
      context: Api
      target: backutopia
    environment:
      - PORT=8000
      - docker_password=${password_docker}
      - PGPASSWORD=${password_docker}
      - remoteorlocal=${remoteorlocal}
      - JWT_SECRET=${JWT_SECRET}
      - _MJ_APIKEY_PUBLIC=${_MJ_APIKEY_PUBLIC}
      - _API_SECRET=${_API_SECRET}
      - sender_email=${sender_email}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 8000:8000
    networks:
    - utopia-network
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: Jobclient
      target: frontutopia
    ports:
      - 80:80
    depends_on:
      - backend

  db:
    build:
      context: Api\db_data
      target: jobgre
    networks:
       utopia-network:
         aliases:
           - postgresForUtopia
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  utopia-network:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
         type: none
         o: bind
         device: .\db_volume

secrets:
  db-password:
    file: db_password.txt
